### ISSUE TITLE
Recrear ambiente de DEV

### ISSUE THREAD

**Issue by prunacomar** [poblaciones/poblaciones#36]
Buenas, me ecnontré con este proyecto, que me pareció genial.

Estoy tratando de configurar el proyecto para desarrollo en un servidor Linux.

- En frontend/node_modules/babel-loader/lib/cache.js fue necesario cambiar:
```
const fs = require('fs/promises');
```
 por esta otra línea:
```
const fs = require('fs').promises;
```

- Hay un problema por mayúsculas/minúsculas con una librería. Se tuvo que cambiar a minúsculas esta carpeta:
```
frontend/src/backoffice/views/Dataset
```

- Hay una URL fija configurada en `frontend/config/dev.env.js:11`

Pese a esto, no logro aún que funcione. Veo que obtengo un error 500 en la llamada a https://desa.poblaciones.org:8000/services/GetConfiguration , sin mucho detalle o log extra.
Alguna idea de cómo avanzar?

**Comment by pablodegrande** [comment]
Buen día. Gracias por escribirnos.

Para tener mejor información de debug, es importante que el php.ini tenga puestas las opciones de mostrar errores. Luego en el config de la aplicación (settings/config.php) debe estar puesto App::SetDebug(true);

**Comment by pablodegrande** [comment]
Un comentario más. Cambiar a minúsculas la carpeta no sería correcto, porque en las menciones en el código aparece @/backoffice/views/Dataset/ (en todos los imports).... a excepción de 1! (en MetricsTab.vue). Que acabamos de corregir a partir de su mensaje.

**Comment by prunacomar** [comment]
Hola Pablo, muchas gracias por tu respuesta súper rápida 👍 

Al activar los logs, veo este error:
```
<b>Fatal error</b>:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class &quot;Context&quot; from namespace &quot;minga\framework&quot;.
Did you forget a &quot;use&quot; statement for e.g. &quot;JMS\Serializer\Context&quot;, &quot;HTMLPurifier_Context&quot;, &quot;phpDocumentor\Reflection\Types\Context&quot; or &quot;Mpdf\Log\Context&quot;? in /app/poblaciones/poblaciones/services/src/app.php:28
Stack trace:
#0 /app/poblaciones/poblaciones/services/startup.php(43): require_once()
#1 /app/poblaciones/poblaciones/services/web/index.php(9): require_once('...')
#2 /app/poblaciones/poblaciones/services/web/resolve-dev.php(16): require_once('...')
#3 {main}
  thrown in <b>/app/poblaciones/poblaciones/services/src/app.php</b> on line <b>28</b><br />
```

Nota para quienes consulten esto a futuro, el archivo de config es al revés (config/settings.php), pero la opción de debug ya venía activada.

**Comment by pablodegrande** [comment]
minga\framework es un submódulo... puede que un update de los submódulos en git lo traiga (en caso de que no lo tuvieras). El archivo que deberías tener es services/src/framework/src/Context.

Si ves que la instalación se sigue trabando, no descartes la posiblidad de enviarme un email y vemos de coordinar algún meet para hacerlo más ágil.

**Comment by prunacomar** [comment]
Veo la carpeta services/src/framework/ vacía. No sé si eso habrá tenido relación con el paso de `git submodule update` en la guía de instalación (lo ejecuté, pero no pareció que haya hecho nada). La llamada puede ser una gran opción. Mi mail es andres@pruna.com.ar

**Comment by pablodegrande** [comment]
Sí, seguro tiene que ver con que baje los submódulos entonces. Quizás haga falta init antes... podrías probar:

$ git submodule init
$ git submodule update

(en otro lado en lugar de eso hacían git submodule update --remote)

**Comment by prunacomar** [comment]
Gracias! Efectivamente, faltaba ese primer init. Ahora eso funcionó.

El siguiente error lo da en el servicio https://desa.poblaciones.org:8000/services/clipping/GetDefaultFrame , y dice:
`FUNCTION poblaciones.GeometryAreaSphere does not exist`

Busqué en dbscript-v1.sql y en argentina_v2.23.sql pero no veo que se defina ahí esa función para la BD.

**Comment by pablodegrande** [comment]
Después de levantar argentina_v2.23.sql tenés que poner la base al día del último script. 

Para eso hay una tabla "version" donde (si hacés select * from version) vas a ver que tenés un registro "DB" que en ver_value te va a decir cuál es el último script corrido en ese dump. 

Si por ejemplo es 60, tenés que ejecutar de la carpeta /startup/scripts todos los scripts hasta el actual a partir del 61 (no recuerdo hasta en versión de base extrajimos la v2.23.sql, pero en la tabla version lo vas a tener. Con esos scripts que vas a correr vas a poder actualizar progresivamente los cambios que hubo en la base desde entonces, incluidas funciones como la que te está faltando. 

Vas a ver que cada script va poniendo el registro en "version" con el número correspondiente, de modo que siempre sepas por dónde está tu base (si bien no es muy frecuente que ocurra, puede que más adelante hagas pull hacia una versión más nueva de fuentes y tengas que correr algún script nuevo)

**Comment by pablodegrande** [comment]
Hola. Repasando los pasos de instalación vi que indica comenzar la base desde el script dbscript-v1.sql, lo que está desactualizado, pues hay scripts más nuevos para iniciar la base y tenerla casi 100% al día. El último en el repo es [dbscript-v3.08.sql](https://github.com/poblaciones/poblaciones/blob/master/startup/dbscript-v3.08.sql). Deberías restaurar a partir de ese. Saludos

**Comment by prunacomar** [comment]
Gracias! Sobre la ejecución de los scripts, primero los ejecuté con el usuario que creé para la App, pero le faltaban permisos. Usando el nuevo script y el usuario root, veo igual un par de temas:

- dbscript-v3.08.sql:
`ERROR 1418 (HY000) at line 783: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)` 

Por ahora lo solucione agregando esta linea al principio del script:
`SET GLOBAL log_bin_trust_function_creators = 1;`

- argentina_v2.23.sql
`ERROR 1452 (23000) at line 29: Cannot add or update a child row: a foreign key constraint fails (`poblaciones`.`clipping_region`, CONSTRAINT `clipping_region_ibfk_1` FOREIGN KEY (`clr_metadata_id`) REFERENCES `metadata` (`met_id`))`

(si lo ejecuto con otras alternativas que no se interrumpen en un error, tengo mucha cantidad de errores, y no estoy seguro si algunos son por arrastre de los anteriores).

**Comment by prunacomar** [comment]
Buenas. Como les comentaba, sugiero agregar esta línea al comienzo del `dbscript-v3.08.sql`:
`SET GLOBAL log_bin_trust_function_creators = 1;`

Respecto a los problemas de FOREIGN KEY en `argentina_v2.23.sql`, recordé que en MySQL los dumps suelen estar desordenados. La solución pasa por deshabilitar los checks antes de ejecutarlo, haciendo:
`SET foreign_key_checks = 0`

Ahora le ejecución fue mucho mejor, aunque llegué a ver al menos 2 errores que se repiten varias veces cada uno:
```
ERROR 1364 (HY000): Field 'cli_geometry_r2' doesn't have a default value
ERROR 1062 (23000): Duplicate entry '1' for key 'user.PRIMARY'
```

Esto por ahora impacta - al menos - en el servicio `/services/clipping/GetDefaultFrame`, donde falla con este error:

<html><body>


(1/1)                                     PublicException                                                                  La vista de regiones de recorte no tiene datos. Contacte a un administrador para solicitar que la vista sea reconstruida.
--
in ClippingService.php line 108
at ClippingService->GetDefaultFrameRegion()in ClippingService.php line 37


</body>
</html>

Alguna idea?

Por otro lado, confirmo que con el fix en la ruta de frontend/build/dev-server.js ahora la parte de logs funciona ok.

**Comment by prunacomar** [comment]
Buenas! Acabo de ver posteada una versión nueva de la estructura de la base. En la versión que usé yo (3.08), encontramos que modificando 3 columnas (para quitar el NOT NULL) se logra después importar el datapack. Podés verlo en https://github.com/poblaciones/poblaciones/compare/master...prunacomar:poblaciones:master-1

**Comment by pablodegrande** [comment]
Sí... estoy por responder, pero no quería responder hasta que no se termine de hacer todo commit =)

**Comment by pablodegrande** [comment]
Generé un nuevo script de inicio de base (para que no tengas que correr los scripts de actualización en cada prueba), y un nuevo datapack. Probando el anterior surgió que algunas cosas (más allá de los errores) no estaban incluidas, así que resulta mejor tener un datapack nuevo.

Los scripts nuevos tienen agregados los SET foreign_key_checks = 0; y el SET GLOBAL log_bin_trust_function_creators = 1;

* El script nuevo de creación para versión 3.10 es: https://github.com/poblaciones/poblaciones/blob/master/startup/dbscript-v3.10.sql
* El data-pack nuevo en https://github.com/poblaciones/data-packs/tree/master/argentina/v3.10 (está todavía subiendo)

Si precisás seguir con la base que levantaste desde el 3.08, lo podés hacer sin problemas (y usar el datapack nuevo), lo que sí vas a precisar es actualizar los scripts de /startup/scripts.

El error de "la vista de regiones de recorte no tiene datos" seguramente sea por no haber regenerado las vistas desde desa.poblaciones.org:8000/logs/caches. Son los botones de "Geografías", "Regiones por geografías" y "Delimitaciones y regiones", que completan la levantada del data-pack.

**Comment by pablodegrande** [comment]
Con lo de poner en nulo geometrías, ojo, porque esos cambios deberían tener valores. Si algo del parseo o el insert los deja en nulo, vendrán problemas después. Si es para probar un ambiente de desarrollo, seguramente no sea problema, pero no debería quedar eso así en un servidor de producción. Mysql y nulos para datos especiales no van bien juntos =)

**Comment by prunacomar** [comment]
Si, gracias. Los caches los habia apretado, pero al fallar antes los INSERT, no arreglaban el problema. 

El problema con ponerlos en NULL, es que esos campos no venían en los INSERT del datapack de Argentina. Entonces fue para no trabarme. 

Con lo que te pasé, quedó todo funcionando en 3.08. Igual, después veré de probar los 3.10 que estás publicando. Muchas gracias.

**Comment by pablodegrande** [comment]
Buenísimo. Cualquier cosa nos consultás... Abrazo!

**Comment by prunacomar** [comment]
Nuevamente, excelente soporte!!

Dejo sólo como nota para el armado del ambiente de DEV, la clave de Google Maps va en el archivo frontend/config/dev.env.js
