### ISSUE TITLE
Certificados SSL internos

### ISSUE THREAD

**Issue by prunacomar** [poblaciones/poblaciones#38]
Buenas, cómo están? Estoy viendo de pasar el despliegue que hice en un contenedor local a un servidor Debian, y me encuentro con un error relacionado al tamaño del certificado.

El mensaje dice:
```
...
_tls_common.js:129
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.setSecureContext (_tls_wrap.js:1318:27)
    at Server (_tls_wrap.js:1182:8)
    at new Server (https.js:64:14)
    at Object.createServer (https.js:88:10)
    at Object.start (/app/poblaciones/frontend/build/single-app.js:35:19)
    at /app/poblaciones/frontend/build/dev-server.js:111:12
    at /app/poblaciones/frontend/node_modules/webpack-dev-middleware/lib/context.js:52:9
    at Array.forEach (<anonymous>)
    at /app/poblaciones/frontend/node_modules/webpack-dev-middleware/lib/context.js:51:11
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  library: 'SSL routines',
  function: 'SSL_CTX_use_certificate',
  reason: 'ee key too small',
  code: 'ERR_SSL_EE_KEY_TOO_SMALL'
}
```

Google confirma que las últimas versiones de openssl requieren 2048bits como mínimo, y al mirar el certificado en frontend/certs/valid-ssl-cert.pem veo que dice que es de 1024 bits, y también la clave privada.

Saben si hay algún requerimiento o consideración para generar una nueva clave y certificado?

**Comment by pablodegrande** [comment]
Lo mejor para pasarlo a un servidor va a ser que ese servidor tenga en
apache su certificado
generado para ese fin. De otro modo ningún navegador va a aceptarlo como
seguro....

No sé si el pasarlo a un servidor tiene que ver con que otras personas
puedan consultar la instalación
(es decir, salir del ambiente de desarrollo). Si fuera así, el paso
correcto es compilar los archivos de vuejs en
archivos js que los unifican....

**Comment by prunacomar** [comment]
Gracias.
