### ISSUE TITLE
Error importando un CSV

### ISSUE THREAD

**Issue by prunacomar** [poblaciones/poblaciones#40]
Buenas! Cuando intento importar un CSV para crear un nuevo Dataset, veo que falla con una ventana donde dice "El proceso no ha podido ser completado." Mirando el log, veo que hay un error 500 en la llamada a _/services/backoffice/Dataset/StepMultiImportFile?k=16970556806410000_

El trace muestra:
<html><body>

(1/1)                                     PublicException                                                                  No se ha obtenido ningún resultado en la consulta cuando se esperaba uno.
--
in Db.php line 235
at Db->fetchScalar()in DatasetTable.php line 138
at DatasetTable::CreateNewTableName()in DatasetTable.php line 21

</body>
</html>

Mirando el código, veo que intenta el siguiente query, que no devuelve datos:

```
SELECT max(t) FROM (
SELECT replace(wdd_table, 'tmp_', '') t
FROM work_dataset_draft WHERE wdd_table LIKE 'work_dataset_draft_%'
OR wdd_table LIKE 'tmp_work_dataset_draft_%'
UNION
SELECT replace(
replace(
replace(
replace(
replace(dat_table, '_shard_1_', '_draft_'),
'_shard_2_', '_draft_'),
'_shard_3_', '_draft_'),
'_shard_4_', '_draft_'),
'_shard_5_', '_draft_') t
FROM dataset
UNION
SELECT dat_table t FROM draft_dataset) l;
```

Eso usa 3 tablas, que mirando, tienen la siguiente cantidad de registros cada una:

- work_dataset_draft 0
- dataset 0
- draft_dataset 5

Mirando los queries de creación de datasets (y los usados para ir hasta la versión actual), creo que está ok lo que vi. Saben entonces qué puede estar fallando para no tener datos en las 2 primeras tablas, y no poder avanzar con la carga del Dataset?

**Comment by prunacomar** [comment]
Buenas! Alguna pista con esto? Estuve mirando el código y los scripts de la base pero no logré encontrar una pista de cómo avanzar.

**Comment by pablodegrande** [comment]
Hola... Perdón que no había comprendido el error al mirarlo la semana pasada. Ahí quedó arreglado con el commit a933c763d81fd7c51bb7ce861a05e8cd7fc4049e [https://github.com/poblaciones/poblaciones/commit/a933c763d81fd7c51bb7ce861a05e8cd7fc4049e]

Si bajás la última versión de fuentes ya no deberías tener este problema, que ocurría en el caso particular de tener la base de datos sin ningún dataset importado.

**Comment by prunacomar** [comment]
Gracias! Eso arregló ese problema. Al hacerlo, surgió otro, por un valor que estaba vacío para la variable maxPreviousId en el archivo MetadataMerger.php y que generaba un problema al romper la query:

```
UPDATE draft_dataset_column JOIN 
(SELECT dc_old.dco_id AS dco_old_id, dc_new.dco_id AS dco_new_id, dc_old.dco_caption AS dco_old_caption ,dc_old.dco_caption,dc_old.dco_label,dc_old.dco_column_width,dc_old.dco_field_width,dc_old.dco_decimals,dc_old.dco_format,dc_old.dco_measure,dc_old.dco_alignment,dc_old.dco_use_in_summary,dc_old.dco_use_in_export,dc_old.dco_order
FROM draft_dataset_column dc_old
LEFT JOIN draft_dataset_column dc_new
ON dc_new.dco_variable = dc_old.dco_variable
AND dc_new.dco_dataset_id = 6 AND dc_new.dco_id >  (((( ACA FALTA UN VALOR ))))
WHERE dc_old.dco_dataset_id = 6) matches 
ON dco_id = matches.dco_new_id
SET 
draft_dataset_column.dco_caption = matches.dco_caption, 
draft_dataset_column.dco_label = matches.dco_label, 
draft_dataset_column.dco_column_width = matches.dco_column_width, 
draft_dataset_column.dco_field_width = matches.dco_field_width, 
draft_dataset_column.dco_decimals = matches.dco_decimals, 
draft_dataset_column.dco_format = matches.dco_format, 
draft_dataset_column.dco_measure = matches.dco_measure, 
draft_dataset_column.dco_alignment = matches.dco_alignment, 
draft_dataset_column.dco_use_in_summary = matches.dco_use_in_summary, 
draft_dataset_column.dco_use_in_export = matches.dco_use_in_export, 
draft_dataset_column.dco_order = matches.dco_order
```

Lo arreglé forzando como int esa variable en la inicialización:

`$this->maxPreviousId = intval($maxPreviousId);
`

En la línea 7 del mismo archivo. Creé el https://github.com/poblaciones/poblaciones/pull/41 para compartir ese fix, espero que sirva.

**Comment by prunacomar** [comment]
Buenas! Ya no se presentan errores, pero estoy viendo que igualmente los datos no se terminan de cargar. Con lo cual, tengo dos dudas: alguna idea/pista de qué puedo revisar? Y por otro lado, hay algún log que pueda activar que me ayude a revisar lo que está sucediendo?

**Comment by pablodegrande** [comment]
Si hubiera algún error interno que no se muestre en pantalla, deberías
poder verlo en https://desa.poblaciones.org/logs/errors (es decir,
navegando el servidor de desarrollo, en la parte adminsitrativa).

Probaste de importar otros formatos? Eso puede aproximar un poco si es algo
del formato, o de la importación en general.

------------------
*Pablo De Grande - **IEHS-IGEHCS (UNCPBA) **/ CONICET*
*http://www.aacademica.org/pablo.de.grande
<http://www.aacademica.org/pablo.de.grande> *

**Comment by prunacomar** [comment]
Gracias, parece que tengo una negación con esa URL del log, siempre busco a nivel de archivos en el servidor. Igual, ahí no vi ningún problema. Quizás con la otra opción de logs puedo subir el nivel de detalle (tipo un debug o similar).

Hice una reducción de los datos a un ejemplo bien pequeño en un CSV, con estos datos, y sigue sucediendo lo mismo:

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.3.2.2 (Windows)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


Nº | Longitud | Latitud | flag | Nombre | Numero
-- | -- | -- | -- | -- | --
101 | -58.631245 | -34.768058 |   | Nueva esperanza | 29
102 | -58.623246 | -34.776781 |   | Jardin comunitario | 80


</body>

</html>

**Comment by pablodegrande** [comment]
Hola,

Si lo que pegaste es exacto el contenido, el CSV no deberiá tener
encabezado <title>, etc, sino directamente los datos. Te sugería importar
un archivo .xlsx, por ejemplo, para ver por dónde puede venir la cosa. En
cualquier caso, el CSV debería comenzar con la fila de encabezados de
columna y seguir con las filas de datos...

Saludos!

------------------
*Pablo De Grande - **IEHS-IGEHCS (UNCPBA) **/ CONICET*
*http://www.aacademica.org/pablo.de.grande
<http://www.aacademica.org/pablo.de.grande> *

**Comment by prunacomar** [comment]
Buenas! El contenido es un CSV tradicional, ese HTML es de cuando lo copié acá como tabla, algo que seguramente hice mal.

Mirando los mensajes que van pasando, veo que dice que crea una tabla, importa, etc.

Mirando la BD, veo tablas creadas como por ejemplo de tmp_work_dataset_draft_000001 a 5, y de work_dataset_draft_000006 a 14. La última tiene los datos del CSV. Las columnas dt_col2 y dt_col3 importaron las coordenadas. Quizás después debo identificarlas, pero mi primer problema sigue siendo que la web me dice que no ve datos.

No sé si luego deberían haber pasado a otra tabla, y por eso era también mi consulta sobre un "debug" para que fuese más fácil ver los pasos que va haciendo (incluso si no fallan) y en todo caso revisar si hubo algo que falló sin detalles, o que falta configurar, etc.

saludos!

**Comment by prunacomar** [comment]
Intentando rastrear manualmente ese flujo, veo que el problema parece estar en que la tabla draft_dataset_column está vacia. Entonces, encuentra el draft_dataset, pero no las columnas asociadas. Parece que las mismas serían creadas en el paso 4 de StepMultiImportFile, al trabajar con DraftDatasetColumn. La tabla draft_dataset_column_value_label con la que opera también está vacía.
Pero acá me trabo al no tener claro la causa de esto, o cómo avanzar más fino con las pruebas.

**Comment by pablodegrande** [comment]
Para poder diagnosticar es importante que intentes importar un xlsx u otro
formato. Quizás no valga la pena que mires en el código si el problema es
el archivo.

**Comment by prunacomar** [comment]
Gracias! Es que en realidad empecé la prueba con un xlsx, y no anduvo. Entonces, intentando "simplificar" el escenario para las pruebas, primero lo pasé a CSV (asumiendo que es un formato más simple para su procesamiento) y reduje los datos a un set mínimo:

Nro,Longitud,Latitud,flag,Nombre,Numero
101,-58.631245,-34.768058,,Nueva esperanza,29
102,-58.623246,-34.776781,,Jardin comunitario,80

Al no tener éxito ni mensajes de error, es que estoy rastreando qué falla, y parece tener relación con los headers y las filas. Pero ahí me trabo.
